sudo: required

language: cpp
services:
  - docker

install:
  - docker pull ubuntu:16.04
  - docker build -f leela-zero/Dockerfiles/Dockerfile.base -t leela-zero:base leela-zero
  - docker build -f leela-zero/Dockerfiles/Dockerfile.gpu -t leela-zero:gpu leela-zero
  - curl -O https://zero.sjeng.org/best-network
  - |
   sed \
    -e '93s|^.*$|command = ./leelaz|' \
    -e '94s|^.*$|parameters = --gtp --noponder --weights best-network|' \
    -e '99s|^.*$|command = ./leelaz|' \
    -e '100s|^.*$|parameters = --gtp --noponder --weights best-network|' \
    goreviewpartner/config.ini > config.ini
  - docker build -t grp .
  - docker run grp example.sgf
