sudo: required

language: cpp
services:
  - docker

install:
  - docker pull ubuntu:16.04
  - docker build -f leela-zero/Dockerfiles/Dockerfile.base -t leela-zero:base leela-zero
  - docker build -f leela-zero/Dockerfiles/Dockerfile.gpu -t leela-zero:gpu leela-zero
  - docker build -f Dockerfile -t grp .
  - docker run grp

deploy:
