sudo: required

language: cpp
services:
  - docker

install:
  - docker pull ubuntu:16.04
  - cd leela-zero
  - docker build -f Dockerfiles/Dockerfile.base -t leela-zero:base .
  - docker build -f Dockerfiles/Dockerfile.gpu -t leela-zero:gpu .
  - cd ..
  - docker build -f Dockerfile -t grp .
  - docker run grp

deploy:
